io:
  input_data_path: "path-to-raw-data"
  input_data_file_type: json
  output_items_path: "path-to-the-output-dir-for-item-sessions-map"
  output_sessions_path: "path-to-the-output-dir-for-session-items-map"
  output_users_path: "path-to-the-output-dir-for-user-sessions-map"
properties:
  sessions:
    actions:
      # Add here action_name: weight
      # example:
      # add_to_cart: 0.5
      # payment: 1
    # The name of the event that is a transaction
    final_action_name: payment
    minimum_session_length: 3
  items:
    minimum_no_of_sessions: 3